### PR TITLE
remake user fields

### PR DESCRIPTION
**Pull request by yangr0**

### CODE REVIEW

**Review by adhi-thirumala — CHANGES_REQUESTED** [review]
why is this all in one db, shouldnt we have both an acct info DB and a profile info DB that are both primary key'd with discord id

**Comment by yangr0** [comment]
How do you want to split this?

profile:
first_name
last_name
dob
pronouns
description
roles
rank

users:
discord_id
riot_id
one_way_matched
two_way_matched

Technically all fall under profile table except one_way_matched and two_way_matched

We could also separate these by private and public information

Or could leave it as it is since there is no security difference and don't have many columns

Let me know what you think

**Comment by adhi-thirumala** [comment]
> How do you want to split this?
> 
> 
> 
> profile:
> 
> first_name
> 
> last_name
> 
> dob
> 
> pronouns
> 
> description
> 
> roles
> 
> rank
> 
> 
> 
> users:
> 
> discord_id
> 
> riot_id
> 
> one_way_matched
> 
> two_way_matched
> 
> 
> 
> Technically all fall under profile table except one_way_matched and two_way_matched
> 
> 
> 
> We could also separate these by private and public information
> 
> 
> 
> Or could leave it as it is since there is no security difference and don't have many columns
> 
> 
> 
> Let me know what you think

i like the public vs private idea, that would make bday a private value since the only thing exposed is age which we could make an api route that auto calculates.

**Comment by yangr0** [comment]
public:
discord_id (primary_key)
first_name
last_name
pronouns
description
roles
rank

private:
discord_id (primary_key)
dob
one_way_matched
two_way_matched

**Comment by yangr0** [comment]
ready to merge

**Review by adhi-thirumala — APPROVED** [review]

**Pull request merged**
